openapi: 3.0.0
info:
  title: Temperature Monitor API
  description: API for monitoring temperature and humidity from a Raspberry Pi with Sense HAT
  version: 1.0.0
servers:
  - url: {SERVER_URL}
    description: Local development server
paths:
  /api/temp:
    get:
      summary: Get current temperature and humidity
      description: Returns the current temperature (in Celsius and Fahrenheit) and humidity readings
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  temperature_c:
                    type: number
                    description: Temperature in Celsius
                    example: 23.5
                  temperature_f:
                    type: number
                    description: Temperature in Fahrenheit
                    example: 74.3
                  humidity:
                    type: number
                    description: Humidity percentage
                    example: 45.2
                  timestamp:
                    type: string
                    description: Time of last reading
                    example: "2023-09-15 14:30:45"
  /api/raw:
    get:
      summary: Get raw temperature data
      description: Returns raw temperature readings including CPU temperature for debugging
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  cpu_temperature:
                    type: number
                    description: CPU temperature in Celsius
                    example: 45.6
                  raw_temperature:
                    type: number
                    description: Raw uncompensated temperature in Celsius
                    example: 29.8
                  compensated_temperature:
                    type: number
                    description: Temperature with CPU heat compensation in Celsius
                    example: 23.5
                  humidity:
                    type: number
                    description: Humidity percentage
                    example: 45.2
                  timestamp:
                    type: string
                    description: Time of last reading
                    example: "2023-09-15 14:30:45" 